if(NOT DEFINED BUILD_DIR OR NOT DEFINED CONFIG)
    message(FATAL_ERROR "BUILD_DIR and CONFIG are required")
endif()
file(MAKE_DIRECTORY "${BUILD_DIR}")
set(stamp "${BUILD_DIR}/.uph-config")
set(old "")
if(EXISTS "${stamp}")
    file(READ "${stamp}" old)
endif()
if(NOT old STREQUAL CONFIG)
    file(WRITE "${stamp}" "${CONFIG}")
endif()